package edu.uga.cs.pcf.services.jobinterview.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-08-24T22:58:16.692-04:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebServiceClient(name = "JobInterviewProcess", 
                  wsdlLocation = "http://localhost:8080/JobInterviewProcess/JobInterviewProcess?wsdl",
                  targetNamespace = "urn:edu.uga.cs.pcf:pcf-services:1.0") 
public class JobInterviewProcess extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:edu.uga.cs.pcf:pcf-services:1.0", "JobInterviewProcess");
    public final static QName JobInterviewProcessPort = new QName("urn:edu.uga.cs.pcf:pcf-services:1.0", "JobInterviewProcessPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/JobInterviewProcess/JobInterviewProcess?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JobInterviewProcess.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/JobInterviewProcess/JobInterviewProcess?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JobInterviewProcess(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JobInterviewProcess(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobInterviewProcess() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JobInterviewProcess(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JobInterviewProcess(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JobInterviewProcess(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns JobInterviewProcessPortType
     */
    @WebEndpoint(name = "JobInterviewProcessPort")
    public JobInterviewProcessPortType getJobInterviewProcessPort() {
        return super.getPort(JobInterviewProcessPort, JobInterviewProcessPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobInterviewProcessPortType
     */
    @WebEndpoint(name = "JobInterviewProcessPort")
    public JobInterviewProcessPortType getJobInterviewProcessPort(WebServiceFeature... features) {
        return super.getPort(JobInterviewProcessPort, JobInterviewProcessPortType.class, features);
    }

}
