package edu.uga.cs.pcf.services.jobinterview.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-08-24T22:58:16.666-04:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "urn:edu.uga.cs.pcf:pcf-services:1.0", name = "JobInterviewProcessPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface JobInterviewProcessPortType {

    @WebResult(name = "interviewResult", targetNamespace = "urn:edu.uga.cs.pcf:pcf-services:1.0", partName = "return")
    @WebMethod(action = "process")
    public InterviewResult process(
        @WebParam(partName = "arg0", name = "interview", targetNamespace = "urn:edu.uga.cs.pcf:pcf-services:1.0")
        Interview arg0
    );
}
