package edu.uga.cs.pcf.services.emergencyreaction.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-08-28T01:32:54.141-04:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebServiceClient(name = "EmergencyReactionWorkflowService", 
                  wsdlLocation = "http://localhost:8080/EmergencyReactionWorkflow/EmergencyReactionWorkflowService?wsdl",
                  targetNamespace = "urn:edu.uga.cs.pcf:pcf-process:1.0") 
public class EmergencyReactionWorkflowService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:edu.uga.cs.pcf:pcf-process:1.0", "EmergencyReactionWorkflowService");
    public final static QName EmergencyReactionWorkflowPort = new QName("urn:edu.uga.cs.pcf:pcf-process:1.0", "EmergencyReactionWorkflowPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EmergencyReactionWorkflow/EmergencyReactionWorkflowService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmergencyReactionWorkflowService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/EmergencyReactionWorkflow/EmergencyReactionWorkflowService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmergencyReactionWorkflowService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmergencyReactionWorkflowService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmergencyReactionWorkflowService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmergencyReactionWorkflowService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmergencyReactionWorkflowService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmergencyReactionWorkflowService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EmergencyReactionWorkflow
     */
    @WebEndpoint(name = "EmergencyReactionWorkflowPort")
    public EmergencyReactionWorkflow getEmergencyReactionWorkflowPort() {
        return super.getPort(EmergencyReactionWorkflowPort, EmergencyReactionWorkflow.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmergencyReactionWorkflow
     */
    @WebEndpoint(name = "EmergencyReactionWorkflowPort")
    public EmergencyReactionWorkflow getEmergencyReactionWorkflowPort(WebServiceFeature... features) {
        return super.getPort(EmergencyReactionWorkflowPort, EmergencyReactionWorkflow.class, features);
    }

}
