package edu.uga.cs.pcf.services.emergencyreaction.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-08-28T01:32:54.104-04:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "urn:edu.uga.cs.pcf:pcf-process:1.0", name = "EmergencyReactionWorkflow")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EmergencyReactionWorkflow {

    @WebResult(name = "EmergencyReactionWorkflowResponse", targetNamespace = "urn:edu.uga.cs.pcf:pcf-process:1.0", partName = "payload")
    @WebMethod(action = "urn:edu.uga.cs.pcf:pcf-process:1.0/process")
    public EmergencyReactionWorkflowResponse process(
        @WebParam(partName = "payload", name = "EmergencyReactionWorkflowRequest", targetNamespace = "urn:edu.uga.cs.pcf:pcf-process:1.0")
        EmergencyReactionWorkflowRequest payload
    );
}
